@baseUrl = http://localhost:5019

### Supplier - Health
GET {{baseUrl}}/api/supplier/health
Accept: application/json

### Supplier - Get All Suppliers
GET {{baseUrl}}/api/supplier/suppliers
Accept: application/json

### Supplier - Get Supplier By Id
GET {{baseUrl}}/api/supplier/suppliers/1
Accept: application/json
