-- PostgreSQL initialization script 
-- Source migration: database/instnwnd.sql

-- ============================================================
-- supplier schema
-- ============================================================

CREATE SCHEMA supplier;

CREATE TABLE supplier.suppliers (
    supplier_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name varchar(40) NOT NULL,
    contact_name varchar(30),
    contact_title varchar(30),
    address varchar(60),
    city varchar(15),
    region varchar(15),
    postal_code varchar(10),
    country varchar(15),
    phone varchar(24),
    fax varchar(24),
    homepage_url text
);

-- ============================================================
-- catalog schema
-- ============================================================

CREATE SCHEMA catalog;

CREATE TABLE catalog.categories (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(15) NOT NULL,
    description text,
    picture bytea
);

CREATE TABLE catalog.products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name varchar(40) NOT NULL,
    supplier_id integer REFERENCES supplier.suppliers (supplier_id),
    category_id integer REFERENCES catalog.categories (category_id),
    quantity_per_unit varchar(20),
    unit_price numeric DEFAULT 0 CONSTRAINT ck_products_unit_price CHECK (unit_price >= 0),
    units_in_stock smallint DEFAULT 0 CONSTRAINT ck_products_units_in_stock CHECK (units_in_stock >= 0),
    units_on_order smallint DEFAULT 0 CONSTRAINT ck_products_units_on_order CHECK (units_on_order >= 0),
    reorder_level smallint DEFAULT 0 CONSTRAINT ck_products_reorder_level CHECK (reorder_level >= 0),
    is_discontinued boolean NOT NULL DEFAULT false
);

CREATE INDEX products_category_id_idx
    ON catalog.products (category_id);

CREATE INDEX products_supplier_id_idx
    ON catalog.products (supplier_id);

-- ============================================================
-- crm schema
-- ============================================================

CREATE SCHEMA crm;

CREATE TABLE crm.customers (
    customer_id varchar(5) PRIMARY KEY,
    company_name varchar(40) NOT NULL,
    contact_name varchar(30),
    contact_title varchar(30),
    address varchar(60),
    city varchar(15),
    region varchar(15),
    postal_code varchar(10),
    country varchar(15),
    phone varchar(24),
    fax varchar(24)
);



