-- init.sql
-- Converted PostgreSQL DDL from instnwnd.sql (SQL Server)
-- Notes:
--  - identity columns use GENERATED BY DEFAULT AS IDENTITY
--  - SQL Server types mapped to Postgres types (nvarchar->varchar, ntext->text, image->bytea, money->numeric(19,4), bit->boolean)
--  - Some SQL Server-specific commands (GO, SET DATEFORMAT, etc.) removed
--  - Procedures from the original script are omitted (left as comments)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- === Bounded-context schemas ===
CREATE SCHEMA IF NOT EXISTS sales_ordering;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS fulfillment;
CREATE SCHEMA IF NOT EXISTS sales_org;
CREATE SCHEMA IF NOT EXISTS supplier;
CREATE SCHEMA IF NOT EXISTS reporting;

-- === Tables ===
SET search_path = sales_org, public;
CREATE TABLE employees (
  employee_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  last_name varchar(20) NOT NULL,
  first_name varchar(10) NOT NULL,
  title varchar(30),
  courtesy_title varchar(25),
  birth_date timestamp without time zone,
  hired_at timestamp without time zone,
  address varchar(60),
  city varchar(15),
  region varchar(15),
  postal_code varchar(10),
  country varchar(15),
  home_phone varchar(24),
  extension varchar(4),
  photo bytea,
  notes text,
  manager_employee_id integer,
  photo_path varchar(255),
  CONSTRAINT "PK_Employees" PRIMARY KEY (employee_id),
  CONSTRAINT "FK_Employees_Employees" FOREIGN KEY (manager_employee_id) REFERENCES sales_org.employees (employee_id),
  CONSTRAINT "CK_Birthdate" CHECK (birth_date < CURRENT_TIMESTAMP)
);
CREATE INDEX "LastName" ON employees (last_name);
CREATE INDEX "PostalCode" ON employees (postal_code);

SET search_path = catalog, public;
CREATE TABLE categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_name varchar(15) NOT NULL,
  description text,
  picture bytea,
  CONSTRAINT "PK_Categories" PRIMARY KEY (category_id)
);
CREATE INDEX "CategoryName" ON categories (category_name);

SET search_path = crm, public;
CREATE TABLE customers (
  customer_id char(5) NOT NULL,
  company_name varchar(40) NOT NULL,
  contact_name varchar(30),
  contact_title varchar(30),
  address varchar(60),
  city varchar(15),
  region varchar(15),
  postal_code varchar(10),
  country varchar(15),
  phone varchar(24),
  fax varchar(24),
  CONSTRAINT "PK_Customers" PRIMARY KEY (customer_id)
);
CREATE INDEX "City" ON customers (city);
CREATE INDEX "CompanyName" ON customers (company_name);
CREATE INDEX "PostalCode_Customers" ON customers (postal_code);
CREATE INDEX "Region_Customers" ON customers (region);

SET search_path = fulfillment, public;
CREATE TABLE shippers (
  shipper_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  company_name varchar(40) NOT NULL,
  phone varchar(24),
  CONSTRAINT "PK_Shippers" PRIMARY KEY (shipper_id)
);

SET search_path = supplier, public;
CREATE TABLE suppliers (
  supplier_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  company_name varchar(40) NOT NULL,
  contact_name varchar(30),
  contact_title varchar(30),
  address varchar(60),
  city varchar(15),
  region varchar(15),
  postal_code varchar(10),
  country varchar(15),
  phone varchar(24),
  fax varchar(24),
  homepage_url text,
  CONSTRAINT "PK_Suppliers" PRIMARY KEY (supplier_id)
);
CREATE INDEX "CompanyName_Suppliers" ON suppliers (company_name);
CREATE INDEX "PostalCode_Suppliers" ON suppliers (postal_code);

SET search_path = sales_ordering, public;
CREATE TABLE orders (
  order_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id char(5),
  employee_id integer,
  ordered_at timestamp without time zone,
  required_at timestamp without time zone,
  shipped_at timestamp without time zone,
  shipper_id integer,
  freight_amount numeric(19,4) DEFAULT 0,
  ship_name varchar(40),
  ship_address varchar(60),
  ship_city varchar(15),
  ship_region varchar(15),
  ship_postal_code varchar(10),
  ship_country varchar(15),
  CONSTRAINT "PK_Orders" PRIMARY KEY (order_id),
  CONSTRAINT "FK_Orders_Customers" FOREIGN KEY (customer_id) REFERENCES crm.customers (customer_id),
  CONSTRAINT "FK_Orders_Employees" FOREIGN KEY (employee_id) REFERENCES sales_org.employees (employee_id),
  CONSTRAINT "FK_Orders_Shippers" FOREIGN KEY (shipper_id) REFERENCES fulfillment.shippers (shipper_id)
);
CREATE INDEX "CustomerID_Orders" ON orders (customer_id);
CREATE INDEX "CustomersOrders" ON orders (customer_id);
CREATE INDEX "EmployeeID_Orders" ON orders (employee_id);
CREATE INDEX "EmployeesOrders" ON orders (employee_id);
CREATE INDEX "OrderDate" ON orders (ordered_at);
CREATE INDEX "ShippedDate" ON orders (shipped_at);
CREATE INDEX "ShipPostalCode" ON orders (ship_postal_code);
CREATE INDEX "ShippersOrders" ON orders (shipper_id);

SET search_path = catalog, public;
CREATE TABLE products (
  product_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_name varchar(40) NOT NULL,
  supplier_id integer,
  category_id integer,
  quantity_per_unit varchar(20),
  unit_price numeric(19,4) DEFAULT 0,
  units_in_stock smallint DEFAULT 0,
  units_on_order smallint DEFAULT 0,
  reorder_level smallint DEFAULT 0,
  is_discontinued boolean NOT NULL DEFAULT false,
  CONSTRAINT "PK_Products" PRIMARY KEY (product_id),
  CONSTRAINT "FK_Products_Categories" FOREIGN KEY (category_id) REFERENCES catalog.categories (category_id),
  CONSTRAINT "FK_Products_Suppliers" FOREIGN KEY (supplier_id) REFERENCES supplier.suppliers (supplier_id),
  CONSTRAINT "CK_Products_UnitPrice" CHECK (unit_price >= 0),
  CONSTRAINT "CK_ReorderLevel" CHECK (reorder_level >= 0),
  CONSTRAINT "CK_UnitsInStock" CHECK (units_in_stock >= 0),
  CONSTRAINT "CK_UnitsOnOrder" CHECK (units_on_order >= 0)
);
CREATE INDEX "CategoryID_Products" ON products (category_id);
CREATE INDEX "CategoriesProducts" ON products (category_id);
CREATE INDEX "ProductName_Products" ON products (product_name);
CREATE INDEX "SupplierID_Products" ON products (supplier_id);
CREATE INDEX "SuppliersProducts" ON products (supplier_id);

SET search_path = sales_ordering, public;
CREATE TABLE order_lines (
  order_id integer NOT NULL,
  product_id integer NOT NULL,
  unit_price numeric(19,4) NOT NULL DEFAULT 0,
  quantity smallint NOT NULL DEFAULT 1,
  discount_rate real NOT NULL DEFAULT 0,
  CONSTRAINT "PK_Order_Details" PRIMARY KEY (order_id, product_id),
  CONSTRAINT "FK_Order_Details_Orders" FOREIGN KEY (order_id) REFERENCES sales_ordering.orders (order_id),
  CONSTRAINT "FK_Order_Details_Products" FOREIGN KEY (product_id) REFERENCES catalog.products (product_id),
  CONSTRAINT "CK_Discount" CHECK (discount_rate >= 0 AND discount_rate <= 1),
  CONSTRAINT "CK_Quantity" CHECK (quantity > 0),
  CONSTRAINT "CK_UnitPrice" CHECK (unit_price >= 0)
);
CREATE INDEX "OrderID_OrderDetails" ON order_lines (order_id);
CREATE INDEX "OrdersOrder_Details" ON order_lines (order_id);
CREATE INDEX "ProductID_OrderDetails" ON order_lines (product_id);
CREATE INDEX "ProductsOrder_Details" ON order_lines (product_id);

-- === Additional Tables (added later in original script) ===

SET search_path = crm, public;
CREATE TABLE customer_demographic_types (
  customer_type_id char(10) NOT NULL,
  customer_description text,
  CONSTRAINT "PK_CustomerDemographics" PRIMARY KEY (customer_type_id)
);

CREATE TABLE customer_demographic_assignments (
  customer_id char(5) NOT NULL,
  customer_type_id char(10) NOT NULL,
  CONSTRAINT "PK_CustomerCustomerDemo" PRIMARY KEY (customer_id, customer_type_id),
  CONSTRAINT "FK_CustomerCustomerDemo" FOREIGN KEY (customer_type_id) REFERENCES crm.customer_demographic_types (customer_type_id),
  CONSTRAINT "FK_CustomerCustomerDemo_Customers" FOREIGN KEY (customer_id) REFERENCES crm.customers (customer_id)
);

SET search_path = sales_org, public;
CREATE TABLE regions (
  region_id integer NOT NULL,
  region_description char(50) NOT NULL,
  CONSTRAINT "PK_Region" PRIMARY KEY (region_id)
);

CREATE TABLE territories (
  territory_id varchar(20) NOT NULL,
  territory_description char(50) NOT NULL,
  region_id integer NOT NULL,
  CONSTRAINT "PK_Territories" PRIMARY KEY (territory_id),
  CONSTRAINT "FK_Territories_Region" FOREIGN KEY (region_id) REFERENCES sales_org.regions (region_id)
);

CREATE TABLE employee_territory_assignments (
  employee_id integer NOT NULL,
  territory_id varchar(20) NOT NULL,
  CONSTRAINT "PK_EmployeeTerritories" PRIMARY KEY (employee_id, territory_id),
  CONSTRAINT "FK_EmployeeTerritories_Employees" FOREIGN KEY (employee_id) REFERENCES sales_org.employees (employee_id),
  CONSTRAINT "FK_EmployeeTerritories_Territories" FOREIGN KEY (territory_id) REFERENCES sales_org.territories (territory_id)
);

-- === Views ===

SET search_path = reporting, sales_ordering, catalog, crm, sales_org, fulfillment, supplier, public;

CREATE VIEW customer_and_suppliers_by_city AS
SELECT city, company_name, contact_name, 'Customers'::text AS relationship
FROM customers
UNION
SELECT city, company_name, contact_name, 'Suppliers'::text
FROM suppliers;

CREATE VIEW alphabetical_list_of_products AS
SELECT p.*, c.category_name
FROM categories c INNER JOIN products p ON c.category_id = p.category_id
WHERE p.is_discontinued = false;

CREATE VIEW current_product_list AS
SELECT p.product_id, p.product_name
FROM products p
WHERE p.is_discontinued = false;

CREATE VIEW orders_with_customer_details AS
SELECT o.order_id, o.customer_id, o.employee_id, o.ordered_at, o.required_at,
  o.shipped_at, o.shipper_id, o.freight_amount, o.ship_name, o.ship_address, o.ship_city,
  o.ship_region, o.ship_postal_code, o.ship_country,
  c.company_name, c.address, c.city, c.region, c.postal_code, c.country
FROM customers c INNER JOIN orders o ON c.customer_id = o.customer_id;

CREATE VIEW products_above_average_price AS
SELECT p.product_name, p.unit_price
FROM products p
WHERE p.unit_price > (SELECT AVG(unit_price) FROM products);

CREATE VIEW products_by_category AS
SELECT c.category_name, p.product_name, p.quantity_per_unit, p.units_in_stock, p.is_discontinued
FROM categories c INNER JOIN products p ON c.category_id = p.category_id
WHERE p.is_discontinued <> true;

CREATE VIEW customers_with_orders AS
SELECT DISTINCT c.customer_id, c.company_name, c.city, c.country
FROM customers c RIGHT JOIN orders o ON c.customer_id = o.customer_id;

CREATE VIEW invoices AS
SELECT o.ship_name, o.ship_address, o.ship_city, o.ship_region, o.ship_postal_code,
  o.ship_country, o.customer_id, c.company_name AS customer_name, c.address, c.city,
  c.region, c.postal_code, c.country,
  (e.first_name || ' ' || e.last_name) AS salesperson,
  o.order_id, o.ordered_at, o.required_at, o.shipped_at, s.company_name AS shipper_name,
  od.product_id, p.product_name, od.unit_price, od.quantity,
  od.discount_rate,
  ROUND((od.unit_price * od.quantity * (1 - od.discount_rate))::numeric, 2) AS extended_price,
  o.freight_amount
FROM shippers s
  INNER JOIN (
    products p INNER JOIN (
      (employees e
        INNER JOIN (customers c INNER JOIN orders o ON c.customer_id = o.customer_id)
        ON e.employee_id = o.employee_id)
      INNER JOIN order_lines od ON o.order_id = od.order_id)
    ON p.product_id = od.product_id)
  ON s.shipper_id = o.shipper_id;

CREATE VIEW order_details_extended AS
SELECT od.order_id, od.product_id, p.product_name,
  od.unit_price, od.quantity, od.discount_rate,
  ROUND((od.unit_price * od.quantity * (1 - od.discount_rate))::numeric, 2) AS extended_price
FROM products p INNER JOIN order_lines od ON p.product_id = od.product_id;

CREATE VIEW order_subtotals AS
SELECT od.order_id,
  SUM(ROUND((od.unit_price * od.quantity * (1 - od.discount_rate))::numeric, 2)) AS subtotal
FROM order_lines od
GROUP BY od.order_id;

CREATE VIEW product_sales AS
SELECT c.category_name, p.product_name,
  SUM(ROUND((od.unit_price * od.quantity * (1 - od.discount_rate))::numeric, 2)) AS product_sales
FROM (categories c INNER JOIN products p ON c.category_id = p.category_id)
  INNER JOIN (orders o INNER JOIN order_lines od ON o.order_id = od.order_id)
  ON p.product_id = od.product_id
GROUP BY c.category_name, p.product_name;

CREATE VIEW category_sales AS
SELECT ps.category_name, SUM(ps.product_sales) AS category_sales
FROM product_sales ps
GROUP BY ps.category_name;

CREATE VIEW sales_by_category AS
SELECT c.category_id, c.category_name, p.product_name,
  SUM(ode.extended_price) AS product_sales
FROM categories c
  INNER JOIN (products p
    INNER JOIN (orders o INNER JOIN order_details_extended ode ON o.order_id = ode.order_id)
    ON p.product_id = ode.product_id)
  ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name, p.product_name;

CREATE VIEW sales_totals_above_amount AS
SELECT os.subtotal AS sale_amount, o.order_id, c.company_name, o.shipped_at
FROM customers c
  INNER JOIN (orders o INNER JOIN order_subtotals os ON o.order_id = os.order_id)
  ON c.customer_id = o.customer_id
WHERE os.subtotal > 2500;

CREATE VIEW shipped_order_subtotals AS
SELECT o.shipped_at, o.order_id, os.subtotal
FROM orders o INNER JOIN order_subtotals os ON o.order_id = os.order_id
WHERE o.shipped_at IS NOT NULL;

CREATE VIEW shipped_order_subtotals_for_yearly_rollup AS
SELECT o.shipped_at, o.order_id, os.subtotal
FROM orders o INNER JOIN order_subtotals os ON o.order_id = os.order_id
WHERE o.shipped_at IS NOT NULL;

-- === Stored Procedures (converted to PL/pgSQL functions) ===

CREATE OR REPLACE FUNCTION cust_orders_detail(p_order_id integer)
RETURNS TABLE(
  product_name varchar,
  unit_price numeric,
  quantity smallint,
  discount integer,
  extended_price numeric
) LANGUAGE sql AS $$
  SELECT
    p.product_name,
    ROUND(od.unit_price, 2) AS unit_price,
    od.quantity,
    CAST(od.discount_rate * 100 AS integer) AS discount,
    ROUND((od.quantity * (1 - od.discount_rate) * od.unit_price)::numeric, 2) AS extended_price
  FROM catalog.products p, sales_ordering.order_lines od
  WHERE od.product_id = p.product_id
    AND od.order_id = p_order_id;
$$;

CREATE OR REPLACE FUNCTION cust_orders_orders(p_customer_id char)
RETURNS TABLE(
  order_id integer,
  ordered_at timestamp,
  required_at timestamp,
  shipped_at timestamp
) LANGUAGE sql AS $$
  SELECT order_id, ordered_at, required_at, shipped_at
  FROM sales_ordering.orders
  WHERE customer_id = p_customer_id
  ORDER BY order_id;
$$;

CREATE OR REPLACE FUNCTION cust_order_hist(p_customer_id char)
RETURNS TABLE(
  product_name varchar,
  total bigint
) LANGUAGE sql AS $$
  SELECT p.product_name, SUM(od.quantity) AS total
  FROM catalog.products p, sales_ordering.order_lines od, sales_ordering.orders o, crm.customers c
  WHERE c.customer_id = p_customer_id
    AND c.customer_id = o.customer_id
    AND o.order_id = od.order_id
    AND od.product_id = p.product_id
  GROUP BY p.product_name;
$$;

CREATE OR REPLACE FUNCTION sales_by_category_report(p_category_name varchar, p_ord_year varchar DEFAULT '1998')
RETURNS TABLE(
  product_name varchar,
  total_purchase numeric
) LANGUAGE plpgsql AS $$
BEGIN
  IF p_ord_year NOT IN ('1996', '1997', '1998') THEN
    p_ord_year := '1998';
  END IF;

  RETURN QUERY
  SELECT
    p.product_name,
    ROUND(SUM((od.quantity * (1 - od.discount_rate) * od.unit_price)::numeric), 0) AS total_purchase
  FROM sales_ordering.order_lines od, sales_ordering.orders o, catalog.products p, catalog.categories c
  WHERE od.order_id = o.order_id
    AND od.product_id = p.product_id
    AND p.category_id = c.category_id
    AND c.category_name = p_category_name
    AND SUBSTRING(TO_CHAR(o.ordered_at, 'YYYY-MM-DD'), 1, 4) = p_ord_year
  GROUP BY p.product_name
  ORDER BY p.product_name;
END;
$$;

CREATE OR REPLACE FUNCTION ten_most_expensive_products()
RETURNS TABLE(
  product_name varchar,
  unit_price numeric
) LANGUAGE sql AS $$
  SELECT p.product_name, p.unit_price
  FROM catalog.products p
  ORDER BY p.unit_price DESC
  LIMIT 10;
$$;

CREATE OR REPLACE FUNCTION employee_sales_by_country(
  p_beginning_date timestamp,
  p_ending_date timestamp
)
RETURNS TABLE(
  country varchar,
  last_name varchar,
  first_name varchar,
  shipped_at timestamp,
  order_id integer,
  sale_amount numeric
) LANGUAGE sql AS $$
  SELECT e.country, e.last_name, e.first_name, o.shipped_at, o.order_id, os.subtotal AS sale_amount
  FROM sales_org.employees e
    INNER JOIN (sales_ordering.orders o INNER JOIN reporting.order_subtotals os ON o.order_id = os.order_id)
    ON e.employee_id = o.employee_id
  WHERE o.shipped_at BETWEEN p_beginning_date AND p_ending_date;
$$;

CREATE OR REPLACE FUNCTION sales_by_year(
  p_beginning_date timestamp,
  p_ending_date timestamp
)
RETURNS TABLE(
  shipped_at timestamp,
  order_id integer,
  subtotal numeric,
  year text
) LANGUAGE sql AS $$
  SELECT o.shipped_at, o.order_id, os.subtotal, TO_CHAR(o.shipped_at, 'YYYY') AS year
  FROM sales_ordering.orders o INNER JOIN reporting.order_subtotals os ON o.order_id = os.order_id
  WHERE o.shipped_at BETWEEN p_beginning_date AND p_ending_date;
$$;
